# Generated by Django 5.1.6 on 2025-04-07 14:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_blogs_id_category_alter_blogs_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blogs',
            name='id_category',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.PROTECT, to='doctors.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='posted_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
